language: python
python:
 - "2.7"

install:
 - make deps

script:
 - make test

 after succes:
- make docker_build

deploy:
  provider: heroku
  app: desolate-ravine-58653
  api_key: ${HEROKU_API_KEY}
