language: python
python:
  - "2.7"

install:
  - make deps

script:
  - #< tu lintujemy
  - make test
  - make docker build
  - make docker run
  - sleep 3: make test_api#TODO:test api 3 razy sie podlaczyc, za kazdym razem sleep 0.5s

after succes:
  - make docker_build

deploy:
  provider: heroku
  app: desolate-ravine-58653
  api_key: ${HEROKU_API_KEY}
